### ISSUE TITLE
Possible version compatibility issue

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/os-lib#77]
Trying to build Mill and sbt plugins with shared code.

Everything was fine with Mill 0.9.6, Scala 3.0.0-RC3 (well, Mill uses 2.13 and sbt uses 2.12 for plugins, and the projects they build are Scala 3.x), and os-lib 0.7.4.

I've upgraded to Mill 0.9.7 and os-lib 0.7.6 (because it's the same as Mill's dep version, tried 0.7.7 too) and I'm getting this error consistently but in one of two places - sometimes in my Mill plugin, sometimes in my sbt plugin:

`java.lang.NoSuchMethodError: 'void os.copy$.apply(os.Path, os.Path, boolean, boolean, boolean, boolean, boolean)'`

The offending line is this one in the shared lib (shared by sbt and Mill) - the last five boolean args are optional but I've tried filling them in too..):

`os.copy(scriptFile, destScriptsFolder / fileName)`

But there are no errors during the build of the library.

Am I (hopefully) missing something or is there an issue here?

**Comment by davesmith00000** [comment]
Ok, I'm not quite sure what I've done differently this morning - maybe a build cache just timed out somewhere - who knows. Anyway, I managed to get a more useful error message by having the arguments explicitly in place:

```bash
[error] ...: one more argument than can be applied to method apply: (from: os.Path, to: os.Path, followLinks: Boolean, replaceExisting: Boolean, copyAttributes: Boolean, createFolders: Boolean)Unit in object copy
[error]       os.copy(gameAssetsDirectoryPath, destAssetsFolder, true, true, true, false, false)
```

When I click though to the library source, it's expecting `mergeFolders`, which is the extra argument from the previous error.

```scala
object copy {
  ...
  def apply(
             from: Path,
             to: Path,
             followLinks: Boolean = true,
             replaceExisting: Boolean = false,
             copyAttributes: Boolean = false,
             createFolders: Boolean = false,
             mergeFolders: Boolean = false
           ): Unit = {
```

So:

- `os.copy(gameAssetsDirectoryPath, destAssetsFolder)` shows the `NoSuchMethodError` message at the point of using the plugin
- `os.copy(gameAssetsDirectoryPath, destAssetsFolder, true, true, true, false, false)` shows a compile error about the extra argument
- `os.copy(gameAssetsDirectoryPath, destAssetsFolder, true, true, true, false)` works as expected.

I also check the dependencies for all projects. The shared lib and sbt are using 0.7.6 cleanly, Mill is using 0.7.6 too, which is explict in Mill's own modules, but it's evicted 0.7.1 from ammonite in a lot of places.

Hope that helps someone.

**Comment by lefou** [comment]
This is caused by pull request https://github.com/com-lihaoyi/os-lib/pull/65 which extends the API. Although I tried to make it binary compatible, it's not source compatible to lower 0.7.x versions. Sorry for that. We should probably have the version bumped to 0.8. 
You can check what brings in the older version with the `ivyDepsTree` target.

**Comment by lefou** [comment]
Actually, the change introduces in #65 is source-compatible, but not binary compatible. So, code compiled to older versions of os-lib (<0.7.5) will no longer find the old method signature of `os.copy.apply` and `os.copy.into.apply`. I opened #80 to fix this. After that we will likely release a 0.7.8 to fix this issue.

**Comment by davesmith00000** [comment]
Great stuff - thanks!
